#!/usr/bin/env bash

# Check if nginx is installed
if ! command nginx -v &>/dev/null; then
  # Install nginx
  apt-get update
  apt-get install nginx -y
else
  echo "Nginx is already installed"
fi

sudo ./setup-config

# Start the nginx server
nginx -g 'daemon off;'
