#!/usr/bin/env bash

# Create the nginx configuration file
sudo cp ./nginx.conf /etc/nginx/nginx.conf

# Copy from dist to the nginx directory
sudo mkdir -p /usr/share/nginx/html/oee-fusion/app
sudo cp -r ./frontend/dist/browser/* /usr/share/nginx/html/oee-fusion/app/

# Copy landing page to the nginx directory
sudo cp -r -t /usr/share/nginx/html/ ./landing-page/*
