#!/usr/bin/env bash

# Create the nginx configuration file
cp ./nginx.conf /etc/nginx/nginx.conf

# Copy from dist to the nginx directory
mkdir -p /usr/share/nginx/html/oee-fusion/app
cp -r ./frontend/dist/browser/* /usr/share/nginx/html/oee-fusion/app/

# Copy landing page to the nginx directory
cp -r -t /usr/share/nginx/html/ ./landing-page/*
