#!/usr/bin/env bash

# Check if nginx is installed
if ! command nginx -v &>/dev/null; then
  ./install-nginx
else
  echo "Nginx is already installed"
fi

# Check if the nginx configuration file is provided
if [ -f "./.env.mode" ]; then
  MODE=$(<./.env.mode)
  if [[ "$MODE" == "dev" ]]; then
    echo "using dev mode"
    ./setup-nginx-dev
  else
    echo "using prod mode"
    ./setup-nginx-prod
  fi
else
    echo "using (default) prod mode"
  ./setup-nginx-prod
fi

