#!/usr/bin/env bash

if [[ "$1" == "--dev" ]]; then
  echo "dev" >./.env.mode
else
  echo "prod" >./.env.mode
fi

sudo ./setup-nginx

# Start the nginx server
if sudo nginx; then
  echo "Nginx server started without error"
else
  echo "Error starting Nginx server"
  exit 1
fi
